In [1]:
import pandas as pd

In [2]:
import geopandas as gpd

In [3]:
import math

In [4]:
import folium

In [5]:
from folium import Choropleth, Circle, Marker
from folium.plugins import HeatMap, MarkerCluster

In [9]:
m_1 = folium.Map(location=[28.0339, 1.6596], tiles='openstreetmap', zoom_start=6)

# Display the map
m_1

In [10]:
import numpy as np

In [12]:
import os
os.environ['SHAPE_RESTORE_SHX'] = 'YES'

In [13]:
danger_zones = gpd.read_file('C:/Users/Century-PC/Desktop/GAM_assurance/rpa99_zones_sismiques.shp')

In [22]:
algerian_communes = pd.read_csv('C:/Users/Century-PC/Desktop/GAM_assurance/rpa99_zones_sismiques.csv')

In [24]:
danger_zones['Wilaya'] = algerian_communes['Wilaya']
danger_zones['Level'] = algerian_communes['Danger_level']

In [30]:
color_map = {
    'Zone 0': 'green',
    'Zone I': 'yellow',
    'Zone II': 'orange',
    'Zone IIa': 'orange',
    'Zone IIb': 'orange',
    'Zone III': 'red'
}

In [32]:
danger_zones.head()

                 geometry Wilaya     Level
0  POINT (1.3667 27.8667)  Adrar    Zone 0
1   POINT (1.3317 36.165)  Chlef  Zone III
2     POINT (2.8833 33.8)  Chlef  Zone IIb
3  POINT (7.1128 35.8781)  Chlef  Zone IIb
4   POINT (6.1742 35.555)  Chlef  Zone IIb

In [ ]:
m_algeria = folium.Map(location=[28.0339, 1.6596], tiles='cartodbpositron', zoom_start=6)

In [40]:
for idx, row in danger_zones.iterrows():
    # Extract latitude and longitude from the POINT geometry
    lat = row.geometry.y
    lon = row.geometry.x
    
    folium.CircleMarker(
        location=[lat, lon],
        radius=10, # Size of the bubble
        color=color_map.get(row['Level'], 'gray'),
        fill=True,
        fill_opacity=0.7,
        popup=f"Wilaya: {row['Wilaya']}<br>Danger: {row['Level']}"
    ).add_to(m_6)

In [41]:
m_6

In [86]:
print(danger_zones.head(10))

                  geometry          Wilaya     Level  zone_score
0   POINT (1.3667 27.8667)           Adrar    Zone 0           0
1    POINT (1.3317 36.165)           Chlef  Zone III           4
2      POINT (2.8833 33.8)           Chlef  Zone IIb           3
3   POINT (7.1128 35.8781)           Chlef  Zone IIb           3
4    POINT (6.1742 35.555)           Chlef  Zone IIb           3
5     POINT (5.0833 36.75)           Chlef  Zone IIb           3
6     POINT (5.7333 34.85)           Chlef  Zone IIb           3
7  POINT (-2.2167 31.6167)           Chlef  Zone IIa           2
8     POINT (2.8289 36.47)        Laghouat    Zone I           1
9     POINT (3.9003 36.38)  Oum El Bouaghi    Zone I           1

In [27]:
sismic_zones = danger_zones

In [31]:
sismic_zones[['Lon', 'Lat']] = sismic_zones['geometry'].astype(str).str.extract(r'\(([-?0-9.]+) ([-?0-9.]+)\)')
sismic_zones[['Lon', 'Lat']] = sismic_zones[['Lon', 'Lat']].astype(float)

In [32]:
sismic_zones.head()

                 geometry Wilaya     Level     Lon      Lat
0  POINT (1.3667 27.8667)  Adrar    Zone 0  1.3667  27.8667
1   POINT (1.3317 36.165)  Chlef  Zone III  1.3317  36.1650
2     POINT (2.8833 33.8)  Chlef  Zone IIb  2.8833  33.8000
3  POINT (7.1128 35.8781)  Chlef  Zone IIb  7.1128  35.8781
4   POINT (6.1742 35.555)  Chlef  Zone IIb  6.1742  35.5550

In [46]:
m_2 = folium.Map(location=[32.0339, 1.6596], tiles='cartodbpositron', zoom_start=6)

In [ ]:

weights = {'Zone 0': 0.1, 'Zone I': 0.2, 'Zone IIa': 0.4, 'Zone IIb': 0.7, 'Zone III': 0.9}
sismic_zones['Weight'] = sismic_zones['Level'].map(weights)

from folium.plugins import HeatMap

data = sismic_zones[['Lat', 'Lon', 'Weight']].values.tolist()
HeatMap(data, radius=15, blur=10).add_to(m_2)

In [48]:
m_2